hugoblox:
  schema: "2.0"
  identity:
    name: Isaiah Byrdsong
    type: person
    tagline: Cyber and Intel Security Professional
    description: "Analytical Security Professional and Intelligence/Cyber Master’s candidate with a Bachelor’s in Intelligence & Analysis. "
  theme:
    mode: system
    pack: dracula
    colors:
      primary: ""
      secondary: ""
      neutral: ""
  typography:
    font: sans
    size: md
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: true
    theme_toggle: true
    cta:
      enable: true
      text: Check out my Linkedln as well!
      url: https://www.linkedin.com/in/ibyrdsong/
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: © {year} {name}
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: true
  privacy:
    enable: true
  analytics:
    google:
      measurement_id: G-SWH53HZ5WW
